### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by gzzen** [erliuu/dsci-310-group-17#15]
Below is a list of feedback that you can make use of to improve your project. If anything is unclear, please feel free to ask questions under this issue thread. We are looking forward to see your next milestone!

### README.md

- [x] Please improve one or more incomplete documentation (i.e., license information, dependencies) (-1)

### Data folder

- [x] Please remove the empty file, `test.md` inside the analysis folder  (-1)

### Project organization

- [x] Please make sufficient use of Github project board by associating Github issue cards into the board. The project board should show the current status of the project to the team. (-5)

### Doucmentation provided for reproducing the report

- [x] Usage documentation could be improved for clarity (i.e., it is not explicitly clear to the user how to use the project, or some of the wording is confusing) (-1)

- [x] Please clearly specify usage instructions to the point a user could copy and paste them and they would work (-1)
- [x] The `jupyter lab` command from the instruction does not open the file directory of the report inside the container (-2)
