### ISSUE TITLE
Milestone 3 feedback

### ISSUE THREAD

**Issue by gzzen** [erliuu/dsci-310-group-17#41]
# Milestone 3
- [x] Please improve the readability of `clean_data_script.py` by including documentation and comments (-1)
- [x] Please further abstract the analysis code presented in `.ipynb` document. The literate code document's sole job is to narrate your analysis, display your analysis artifacts (-3)
- [x] Please ensure every feature & fix to be operated under a separate branch (-1)
- [x] Please include more detailed instruction in the procedure of generating the report, i.e., where to find the analysis output and report, how to use `make clean`, assuming that the viewer knows nothing about the project structure (-1)

# Addressment of previous feedback
The parts that appeared on previous milestone feedback, and has been addressed adequately is labelled with `addressed`, and 50% marks are given back.
- #15 (all addressed) (+5.5)
- #28 (all addressed) (+3.5)
